version: 3

tasks:
  update-version:
    desc: Update the version
    vars:
      VERSION:
        sh: gitversion
    cmd: |
      echo "package main
      var version = \"{{.VERSION}}\"" > cmd/protoc-gen-go-nats/version.go
  build:
    desc: Build the plugin
    deps:
      - update-version
    cmds:
      - go build -o protoc-gen-go-nats cmd/protoc-gen-go-nats/*.go
  run:
    desc: Run the plugin
    deps:
      - update-version
    cmds:
      - go run cmd/protoc-gen-go-nats/*.go -v
  install:
    desc: Install the plugin
    deps:
      - build
    cmds:
      - cp protoc-gen-go-nats ~/go/bin/protoc-gen-go-nats
  test:
    desc: Run tests
    cmds:
      - go test -parallel 8 -v ./...
  proto:
    desc: Generate protobuf files
    cmds:
      - fd -t f -e proto . internal/test -x protoc -I$(go list -m -f '{{ "{{ .Dir }}" }}' xiam.li/protonats)/proto -I internal/test --go_out=internal/test --go_opt=paths=source_relative --go-nats_out=internal/test --go-nats_opt=paths=source_relative {}
  helloworld:
    desc: Generate protobuf files for helloworld example
    cmds:
      - protoc -I$(go list -m -f '{{ "{{ .Dir }}" }}' xiam.li/protonats)/proto -I internal/helloworld --go_out=internal/helloworld --go_opt=paths=source_relative --go-nats_out=internal/helloworld --go-nats_opt=paths=source_relative internal/helloworld/helloworld.proto
