// Code generated by protoc-gen-go-nats. DO NOT EDIT.
// Versions:
// - protoc-gen-go-nats v0.1.14-dev.3+dirty
// - protoc        v6.33.0
// source: helloworld.proto

package pb

import (
	context "context"
	json "encoding/json"
	errors "errors"
	nats_go "github.com/nats-io/nats.go"
	micro "github.com/nats-io/nats.go/micro"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	sync "sync"
	time "time"
	impl "xiam.li/protonats/go/impl"
	protonats "xiam.li/protonats/go/protonats"
)

// region Client
type HelloWorldServiceNATSClient interface {
	HelloWorld(req *HelloWorldRequest, opts ...protonats.CallOption) (*HelloWorldResponse, error)
	SetTimeout(time.Duration)
	// ListInstances returns a list containing all instances of this service
	// This is a convenience method that calls protonats.Ping with no options
	ListInstances() ([]*protonats.Ping, error)
	// Ping sends a ping to either all instances or a specific instance of this service
	Ping(opts ...protonats.CallOption) ([]*protonats.Ping, error)
	// Stats returns the stats of either all instances or a specific instance of this service
	Stats(opts ...protonats.CallOption) ([]*micro.Stats, error)
	// Info returns the info of either all instances or a specific instance of this service
	Info(opts ...protonats.CallOption) ([]*micro.Info, error)
}

type helloWorldServiceNATSClient struct {
	nc      *nats_go.Conn
	timeout time.Duration
}

func (c *helloWorldServiceNATSClient) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *helloWorldServiceNATSClient) ListInstances() ([]*protonats.Ping, error) {
	return c.Ping()
}

func (c *helloWorldServiceNATSClient) Stats(opts ...protonats.CallOption) ([]*micro.Stats, error) {
	objs, _, err := request(c.nc, c.timeout, "$SRV.STATS.HelloWorldService", nil, func(data []byte, rtt time.Duration) (*micro.Stats, error) {
		var obj micro.Stats
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *helloWorldServiceNATSClient) Info(opts ...protonats.CallOption) ([]*micro.Info, error) {
	objs, _, err := request(c.nc, c.timeout, "$SRV.INFO.HelloWorldService", nil, func(data []byte, rtt time.Duration) (*micro.Info, error) {
		var obj micro.Info
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *helloWorldServiceNATSClient) Ping(opts ...protonats.CallOption) ([]*protonats.Ping, error) {
	objs, _, err := request(c.nc, c.timeout, "$SRV.PING.HelloWorldService", nil, func(data []byte, rtt time.Duration) (*protonats.Ping, error) {
		var obj protonats.Ping
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		obj.RTT = rtt
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *helloWorldServiceNATSClient) handleWithRetry(req proto.Message, subject string, out proto.Message, opts ...protonats.CallOption) (err error) {
	options := impl.ProcessCallOptions(opts...)
	timeout := options.GetTimeoutOr(c.timeout)

	var tries int
	for {
		err = c.handle(options.Context, req, options.Subject(subject), out, timeout)
		if err == nil || !errors.Is(err, nats_go.ErrNoResponders) {
			return
		}
		tries++
		if !options.ShouldRetry() {
			return
		}
		if options.Context != nil && options.Context.Err() != nil {
			err = errors.Join(err, options.Context.Err())
			return
		}
		if tries >= options.Retries {
			err = errors.New("Failed to call service after max tries: " + err.Error())
			return
		}
		time.Sleep(options.RetryDelay)
	}
}
func (c *helloWorldServiceNATSClient) handle(ctx context.Context, req proto.Message, subject string, out proto.Message, timeout time.Duration) (err error) {
	var data []byte
	if req != nil {
		if data, err = proto.Marshal(req); err != nil {
			return protonats.ErrMarshallingFailed
		}
	}
	var msg *nats_go.Msg
	if ctx == nil {
		msg, err = c.nc.Request(subject, data, timeout)
	} else {
		msg, err = c.nc.RequestWithContext(ctx, subject, data)
	}
	if err != nil {
		return err
	}
	if errMsg, errCode := msg.Header.Get(micro.ErrorHeader), msg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
		if len(msg.Data) == 0 {
			return protonats.ServiceError{errCode, errMsg, ""}
		}
		return protonats.ServiceError{errCode, errMsg, string(msg.Data)}
	}
	if out != nil {
		if err = proto.Unmarshal(msg.Data, out); err != nil {
			return protonats.ErrUnmarshallingFailed
		}
	}
	return nil
}

func request[T any](conn *nats_go.Conn, timeout time.Duration, subject string, data []byte, collector func([]byte, time.Duration) (*T, error), opts ...protonats.CallOption) ([]*T, []protonats.ServiceError, error) {
	options := impl.ProcessCallOptions(opts...)
	timeout = options.GetTimeoutOr(timeout)

	ctx, cancel := context.WithTimeout(options.Ctx(), timeout)
	defer cancel()

	timer := time.NewTimer(timeout)
	go func() {
		select {
		case <-timer.C:
			cancel()
		case <-ctx.Done():
			timer.Stop()
			return
		}
	}()
	var start time.Time
	res := []*T{}
	mu := sync.Mutex{}
	errCh := make(chan error)
	serviceErrs := []protonats.ServiceError{}
	var finisher *time.Timer
	if !options.DisableFinisher {
		finisher = time.NewTimer(timeout)
		go func() {
			select {
			case <-finisher.C:
				cancel()
			case <-ctx.Done():
				return
			}
		}()
	}
	sub, err := conn.Subscribe(conn.NewRespInbox(), func(msg *nats_go.Msg) {
		mu.Lock()
		defer mu.Unlock()

		rtt := time.Since(start)
		if msg.Header.Get("Status") == "503" {
			errCh <- nats_go.ErrNoResponders
			return
		}

		if finisher != nil {
			finisher.Reset(250 * time.Millisecond)
		}

		if errMsg, errCode := msg.Header.Get(micro.ErrorHeader), msg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
			if len(msg.Data) == 0 {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg})
			} else {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg, Details: string(msg.Data)})
			}
			return
		}
		if collector != nil {
			if col, err := collector(msg.Data, rtt); err != nil {
				errCh <- err
			} else {
				res = append(res, col)
			}
		}
	})
	if err != nil {
		return nil, nil, err
	}
	defer sub.Unsubscribe()

	start = time.Now()
	err = conn.PublishRequest(options.Subject(subject), sub.Subject, data)
	if err != nil {
		return nil, nil, err
	}

	select {
	case err = <-errCh:
		return nil, serviceErrs, err
	case <-ctx.Done():
		return res, serviceErrs, nil
	}
}

func NewHelloWorldServiceNATSClient(nc *nats_go.Conn) HelloWorldServiceNATSClient {
	return &helloWorldServiceNATSClient{nc: nc, timeout: time.Second * 5}
}

func (c *helloWorldServiceNATSClient) HelloWorld(req *HelloWorldRequest, opts ...protonats.CallOption) (*HelloWorldResponse, error) {
	var response HelloWorldResponse

	if err := c.handleWithRetry(req, "service.HelloWorldService.HelloWorld", &response, opts...); err != nil {
		return nil, err
	}
	return &response, nil
}

//endregion

// region Server
type HelloWorldServiceNATSServer interface {
	HelloWorld(req *HelloWorldRequest) (*HelloWorldResponse, error)
}

type HelloWorldServiceId interface {
	SetHelloWorldServiceId(string)
}

func NewHelloWorldServiceNATSServer(nc *nats_go.Conn, server HelloWorldServiceNATSServer, opts ...protonats.ServerOption) micro.Service {
	service, options, err := impl.NewService("HelloWorldService", nc, server, opts...)
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	if setId, ok := server.(HelloWorldServiceId); ok {
		setId.SetHelloWorldServiceId(service.Info().ID)
	}
	_newHelloWorldServiceServer(service, server, options)

	return service
}
func _newHelloWorldServiceServer(service micro.Service, server HelloWorldServiceNATSServer, opts *impl.ServerOpts) {
	var err error
	_ = err

	// Register the service's methods
	HelloWorldHandler := micro.HandlerFunc(func(request micro.Request) {
		var req HelloWorldRequest
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		response, err := server.HelloWorld(&req)
		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("HelloWorld", HelloWorldHandler, opts.Subject("service.HelloWorldService.HelloWorld", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("HelloWorld-Direct", HelloWorldHandler, opts.Subject("service.HelloWorldService.HelloWorld", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

}

//endregion
