// Code generated by protoc-gen-go-nats. DO NOT EDIT.
// Versions:
// - protoc-gen-go-nats v0.1.14-dev.21+dirty
// - protoc        v6.33.0
// source: test.proto

package test

import (
	context "context"
	json "encoding/json"
	errors "errors"
	nats_go "github.com/nats-io/nats.go"
	micro "github.com/nats-io/nats.go/micro"
	nuid "github.com/nats-io/nuid"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	sync "sync"
	time "time"
	impl "xiam.li/protonats/go/impl"
	protonats "xiam.li/protonats/go/protonats"
)

// region Client
type TestServiceNATSClient interface {
	// Normal tests
	NormalTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	NormalEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error)
	NormalTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error
	NormalEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error
	// Methods that will expect an error in the test implementation
	ErrServiceError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	ErrServerError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	ErrServiceErrorBroadcast(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	ErrServerErrorBroadcast(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	// Normal tests with broadcast option
	NormalBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	NormalBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	NormalBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	NormalBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	// Leader option tests
	LeaderOnlyTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	LeaderOnlyEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error)
	LeaderOnlyTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error
	LeaderOnlyEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error
	// Leader with broadcast option tests
	LeaderOnlyBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	LeaderOnlyBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	LeaderOnlyBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	LeaderOnlyBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	// Follower option tests
	FollowerOnlyTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	FollowerOnlyEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error)
	FollowerOnlyTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error
	FollowerOnlyEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error
	// Follower with broadcast option tests
	FollowerOnlyBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	FollowerOnlyBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	FollowerOnlyBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	FollowerOnlyBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	// Special cases
	ThreeSecondDelay(ctx context.Context, opts ...protonats.CallOption) error
	SetTimeout(time.Duration)
	// ListInstances returns a list containing all instances of this service
	// This is a convenience method that calls protonats.Ping with no options
	ListInstances(ctx context.Context) ([]*protonats.Ping, error)
	// Ping sends a ping to either all instances or a specific instance of this service
	Ping(ctx context.Context, opts ...protonats.CallOption) ([]*protonats.Ping, error)
	// Stats returns the stats of either all instances or a specific instance of this service
	Stats(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Stats, error)
	// Info returns the info of either all instances or a specific instance of this service
	Info(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Info, error)
}

type testServiceNATSClient struct {
	nc          *nats_go.Conn
	timeout     time.Duration
	interceptor protonats.UnaryClientInterceptor
}

func (c *testServiceNATSClient) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *testServiceNATSClient) ListInstances(ctx context.Context) ([]*protonats.Ping, error) {
	return c.Ping(ctx)
}

func (c *testServiceNATSClient) Stats(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Stats, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.STATS.TestService", nil, func(data []byte, rtt time.Duration) (*micro.Stats, error) {
		var obj micro.Stats
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) Info(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Info, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.INFO.TestService", nil, func(data []byte, rtt time.Duration) (*micro.Info, error) {
		var obj micro.Info
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) Ping(ctx context.Context, opts ...protonats.CallOption) ([]*protonats.Ping, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.PING.TestService", nil, func(data []byte, rtt time.Duration) (*protonats.Ping, error) {
		var obj protonats.Ping
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		obj.RTT = rtt
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) handle(ctx context.Context, req proto.Message, info *protonats.MethodInfo, out proto.Message, opts ...protonats.CallOption) (err error) {
	var headerMap nats_go.Header
	if ctxHeaders := protonats.HeadersFromOutgoingContext(ctx); ctxHeaders != nil {
		headerMap = nats_go.Header(ctxHeaders)
		for key, values := range headerMap {
			headerMap[key] = values
		}
	} else {
		headerMap = nats_go.Header{}
	}

	invoker := invoker(c.nc)

	if c.interceptor == nil {
		return invoker(ctx, info, req, out, headerMap, opts...)
	} else {
		return c.interceptor(ctx, info, req, out, headerMap, invoker, opts...)
	}
}

func invoker(conn *nats_go.Conn) protonats.UnaryInvoker {
	return func(ctx context.Context, info *protonats.MethodInfo, req proto.Message, reply proto.Message, header nats_go.Header, opts ...protonats.CallOption) error {
		options := impl.ProcessCallOptions(opts...)

		var cancel context.CancelFunc
		if _, hasDeadline := ctx.Deadline(); !hasDeadline {
			timeout := options.GetTimeoutOr(5 * time.Second)
			ctx, cancel = context.WithTimeout(ctx, timeout)
			defer cancel()
		}

		data, err := proto.Marshal(req)
		if err != nil {
			return protonats.ErrMarshallingFailed
		}

		subject := options.Subject(info.Subject)
		msg := &nats_go.Msg{
			Subject: subject,
			Data:    data,
			Header:  header,
		}

		respMsg, err := conn.RequestMsgWithContext(ctx, msg)
		if err != nil {
			return err
		}

		if errMsg, errCode := respMsg.Header.Get(micro.ErrorHeader), respMsg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
			if len(respMsg.Data) == 0 {
				return protonats.ServiceError{Code: errCode, Description: errMsg}
			}
			return protonats.ServiceError{Code: errCode, Description: errMsg, Details: string(respMsg.Data)}
		}
		if reply != nil {
			if err = proto.Unmarshal(respMsg.Data, reply); err != nil {
				return protonats.ErrUnmarshallingFailed
			}
		}
		return nil
	}
}

func request[T any](ctx context.Context, conn *nats_go.Conn, timeout time.Duration, subject string, data []byte, collector func([]byte, time.Duration) (*T, error), opts ...protonats.CallOption) ([]*T, []protonats.ServiceError, error) {
	options := impl.ProcessCallOptions(opts...)
	timeout = options.GetTimeoutOr(timeout)

	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	timer := time.NewTimer(timeout)
	go func() {
		select {
		case <-timer.C:
			cancel()
		case <-ctx.Done():
			timer.Stop()
			return
		}
	}()
	var start time.Time
	res := []*T{}
	mu := sync.Mutex{}
	errCh := make(chan error)
	serviceErrs := []protonats.ServiceError{}
	var finisher *time.Timer
	if !options.DisableFinisher {
		finisher = time.NewTimer(timeout)
		go func() {
			select {
			case <-finisher.C:
				cancel()
			case <-ctx.Done():
				return
			}
		}()
	}
	sub, err := conn.Subscribe(conn.NewRespInbox(), func(msg *nats_go.Msg) {
		mu.Lock()
		defer mu.Unlock()

		rtt := time.Since(start)
		if msg.Header.Get("Status") == "503" {
			errCh <- nats_go.ErrNoResponders
			return
		}

		if finisher != nil {
			finisher.Reset(250 * time.Millisecond)
		}

		if errMsg, errCode := msg.Header.Get(micro.ErrorHeader), msg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
			if len(msg.Data) == 0 {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg})
			} else {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg, Details: string(msg.Data)})
			}
			return
		}
		if collector != nil {
			if col, err := collector(msg.Data, rtt); err != nil {
				errCh <- err
			} else {
				res = append(res, col)
			}
		}
	})
	if err != nil {
		return nil, nil, err
	}
	defer sub.Unsubscribe()

	start = time.Now()
	err = conn.PublishRequest(options.Subject(subject), sub.Subject, data)
	if err != nil {
		return nil, nil, err
	}

	select {
	case err = <-errCh:
		return nil, serviceErrs, err
	case <-ctx.Done():
		return res, serviceErrs, nil
	}
}

func NewTestServiceNATSClient(nc *nats_go.Conn, opts ...protonats.ClientOption) TestServiceNATSClient {
	clientOpts := impl.ProcessClientOptions(opts...)
	return &testServiceNATSClient{nc: nc, timeout: time.Second * 5, interceptor: clientOpts.UnaryInterceptor}
}

func (c *testServiceNATSClient) NormalTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalTestTest",
		Service: "TestService",
		Method:  "NormalTestTest",
	}

	return &response, c.handle(ctx, req, info, &response, opts...)
}

func (c *testServiceNATSClient) NormalEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalEmptyTest",
		Service: "TestService",
		Method:  "NormalEmptyTest",
	}

	return &response, c.handle(ctx, nil, info, &response, opts...)
}

func (c *testServiceNATSClient) NormalTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalTestEmpty",
		Service: "TestService",
		Method:  "NormalTestEmpty",
	}

	return c.handle(ctx, req, info, nil, opts...)
}

func (c *testServiceNATSClient) NormalEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalEmptyEmpty",
		Service: "TestService",
		Method:  "NormalEmptyEmpty",
	}

	return c.handle(ctx, nil, info, nil, opts...)
}

func (c *testServiceNATSClient) ErrServiceError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.ErrServiceError",
		Service: "TestService",
		Method:  "ErrServiceError",
	}

	return &response, c.handle(ctx, req, info, &response, opts...)
}

func (c *testServiceNATSClient) ErrServerError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.ErrServerError",
		Service: "TestService",
		Method:  "ErrServerError",
	}

	return &response, c.handle(ctx, req, info, &response, opts...)
}

func (c *testServiceNATSClient) ErrServiceErrorBroadcast(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ErrMarshallingFailed
		}
	}
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.ErrServiceErrorBroadcast", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) ErrServerErrorBroadcast(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ErrMarshallingFailed
		}
	}
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.ErrServerErrorBroadcast", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ErrMarshallingFailed
		}
	}
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.NormalBroadcastTestTest", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.NormalBroadcastEmptyTest", nil, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, protonats.ErrMarshallingFailed
		}
	}
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.NormalBroadcastTestEmpty", data, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.NormalBroadcastEmptyEmpty", nil, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) LeaderOnlyTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.LeaderOnlyTestTest",
		Service: "TestService",
		Method:  "LeaderOnlyTestTest",
	}

	return &response, c.handle(ctx, req, info, &response, opts...)
}

func (c *testServiceNATSClient) LeaderOnlyEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.LeaderOnlyEmptyTest",
		Service: "TestService",
		Method:  "LeaderOnlyEmptyTest",
	}

	return &response, c.handle(ctx, nil, info, &response, opts...)
}

func (c *testServiceNATSClient) LeaderOnlyTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.LeaderOnlyTestEmpty",
		Service: "TestService",
		Method:  "LeaderOnlyTestEmpty",
	}

	return c.handle(ctx, req, info, nil, opts...)
}

func (c *testServiceNATSClient) LeaderOnlyEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.LeaderOnlyEmptyEmpty",
		Service: "TestService",
		Method:  "LeaderOnlyEmptyEmpty",
	}

	return c.handle(ctx, nil, info, nil, opts...)
}

func (c *testServiceNATSClient) LeaderOnlyBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ErrMarshallingFailed
		}
	}
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.LeaderOnlyBroadcastTestTest", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) LeaderOnlyBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.LeaderOnlyBroadcastEmptyTest", nil, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) LeaderOnlyBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, protonats.ErrMarshallingFailed
		}
	}
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.LeaderOnlyBroadcastTestEmpty", data, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) LeaderOnlyBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.LeaderOnlyBroadcastEmptyEmpty", nil, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) FollowerOnlyTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.FollowerOnlyTestTest",
		Service: "TestService",
		Method:  "FollowerOnlyTestTest",
	}

	return &response, c.handle(ctx, req, info, &response, opts...)
}

func (c *testServiceNATSClient) FollowerOnlyEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.FollowerOnlyEmptyTest",
		Service: "TestService",
		Method:  "FollowerOnlyEmptyTest",
	}

	return &response, c.handle(ctx, nil, info, &response, opts...)
}

func (c *testServiceNATSClient) FollowerOnlyTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.FollowerOnlyTestEmpty",
		Service: "TestService",
		Method:  "FollowerOnlyTestEmpty",
	}

	return c.handle(ctx, req, info, nil, opts...)
}

func (c *testServiceNATSClient) FollowerOnlyEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.FollowerOnlyEmptyEmpty",
		Service: "TestService",
		Method:  "FollowerOnlyEmptyEmpty",
	}

	return c.handle(ctx, nil, info, nil, opts...)
}

func (c *testServiceNATSClient) FollowerOnlyBroadcastTestTest(req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ErrMarshallingFailed
		}
	}
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.FollowerOnlyBroadcastTestTest", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) FollowerOnlyBroadcastEmptyTest(opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	objs, serviceErrs, err := request(c.nc, c.timeout, "service.TestService.FollowerOnlyBroadcastEmptyTest", nil, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) FollowerOnlyBroadcastTestEmpty(req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, protonats.ErrMarshallingFailed
		}
	}
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.FollowerOnlyBroadcastTestEmpty", data, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) FollowerOnlyBroadcastEmptyEmpty(opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	_, serviceErrs, err := request[struct{}](c.nc, c.timeout, "service.TestService.FollowerOnlyBroadcastEmptyEmpty", nil, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) ThreeSecondDelay(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.ThreeSecondDelay",
		Service: "TestService",
		Method:  "ThreeSecondDelay",
	}

	return c.handle(ctx, nil, info, nil, opts...)
}

//endregion

// region Server
type TestServiceNATSServer interface {
	// Normal tests
	NormalTestTest(ctx context.Context, req *Test) (*Test, error)
	NormalEmptyTest(ctx context.Context) (*Test, error)
	NormalTestEmpty(ctx context.Context, req *Test) error
	NormalEmptyEmpty(ctx context.Context) error
	// Methods that will expect an error in the test implementation
	ErrServiceError(ctx context.Context, req *Test) (*Test, error)
	ErrServerError(ctx context.Context, req *Test) (*Test, error)
	ErrServiceErrorBroadcast(ctx context.Context, req *Test) (*Test, error)
	ErrServerErrorBroadcast(ctx context.Context, req *Test) (*Test, error)
	// Normal tests with broadcast option
	NormalBroadcastTestTest(ctx context.Context, req *Test) (*Test, error)
	NormalBroadcastEmptyTest(ctx context.Context) (*Test, error)
	NormalBroadcastTestEmpty(ctx context.Context, req *Test) error
	NormalBroadcastEmptyEmpty(ctx context.Context) error
	// Special cases
	ThreeSecondDelay(ctx context.Context) error
	TestServiceNATSLeaderServer
	TestServiceNATSFollowerServer
}

type TestServiceNATSLeaderServer interface {
	// Leader option tests
	LeaderOnlyTestTest(ctx context.Context, req *Test) (*Test, error)
	LeaderOnlyEmptyTest(ctx context.Context) (*Test, error)
	LeaderOnlyTestEmpty(ctx context.Context, req *Test) error
	LeaderOnlyEmptyEmpty(ctx context.Context) error
	// Leader with broadcast option tests
	LeaderOnlyBroadcastTestTest(ctx context.Context, req *Test) (*Test, error)
	LeaderOnlyBroadcastEmptyTest(ctx context.Context) (*Test, error)
	LeaderOnlyBroadcastTestEmpty(ctx context.Context, req *Test) error
	LeaderOnlyBroadcastEmptyEmpty(ctx context.Context) error
}

type TestServiceNATSFollowerServer interface {
	// Follower option tests
	FollowerOnlyTestTest(ctx context.Context, req *Test) (*Test, error)
	FollowerOnlyEmptyTest(ctx context.Context) (*Test, error)
	FollowerOnlyTestEmpty(ctx context.Context, req *Test) error
	FollowerOnlyEmptyEmpty(ctx context.Context) error
	// Follower with broadcast option tests
	FollowerOnlyBroadcastTestTest(ctx context.Context, req *Test) (*Test, error)
	FollowerOnlyBroadcastEmptyTest(ctx context.Context) (*Test, error)
	FollowerOnlyBroadcastTestEmpty(ctx context.Context, req *Test) error
	FollowerOnlyBroadcastEmptyEmpty(ctx context.Context) error
}

type TestServiceId interface {
	SetTestServiceId(string)
}

func NewTestServiceNATSServer(nc *nats_go.Conn, server TestServiceNATSServer, opts ...protonats.ServerOption) micro.Service {
	service, options, err := impl.NewService("TestService", nc, server, opts...)
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	if setId, ok := server.(TestServiceId); ok {
		setId.SetTestServiceId(service.Info().ID)
	}
	_newTestServiceServer(service, server, options)

	if !options.WithoutLeaderFunctions {
		_newTestServiceLeaderServer(service, server, options)
	}
	if !options.WithoutFollowerFunctions {
		_newTestServiceFollowerServer(service, server, options)
	}
	return service
}
func _newTestServiceServer(service micro.Service, server TestServiceNATSServer, opts *impl.ServerOpts) {
	var err error
	_ = err

	// Register the service's methods
	NormalTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.NormalTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("NormalTestTest", NormalTestTestHandler, opts.Subject("service.TestService.NormalTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalTestTest-Direct", NormalTestTestHandler, opts.Subject("service.TestService.NormalTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.NormalEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("NormalEmptyTest", NormalEmptyTestHandler, opts.Subject("service.TestService.NormalEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalEmptyTest-Direct", NormalEmptyTestHandler, opts.Subject("service.TestService.NormalEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.NormalTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("NormalTestEmpty", NormalTestEmptyHandler, opts.Subject("service.TestService.NormalTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalTestEmpty-Direct", NormalTestEmptyHandler, opts.Subject("service.TestService.NormalTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.NormalEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("NormalEmptyEmpty", NormalEmptyEmptyHandler, opts.Subject("service.TestService.NormalEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalEmptyEmpty-Direct", NormalEmptyEmptyHandler, opts.Subject("service.TestService.NormalEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	ErrServiceErrorHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServiceError",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServiceError(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("ErrServiceError", ErrServiceErrorHandler, opts.Subject("service.TestService.ErrServiceError", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("ErrServiceError-Direct", ErrServiceErrorHandler, opts.Subject("service.TestService.ErrServiceError", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	ErrServerErrorHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServerError",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServerError(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("ErrServerError", ErrServerErrorHandler, opts.Subject("service.TestService.ErrServerError", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("ErrServerError-Direct", ErrServerErrorHandler, opts.Subject("service.TestService.ErrServerError", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	ErrServiceErrorBroadcastHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServiceErrorBroadcast",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServiceErrorBroadcast(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("ErrServiceErrorBroadcast-Broadcast", ErrServiceErrorBroadcastHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.ErrServiceErrorBroadcast", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("ErrServiceErrorBroadcast-Direct", ErrServiceErrorBroadcastHandler, opts.Subject("service.TestService.ErrServiceErrorBroadcast", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	ErrServerErrorBroadcastHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServerErrorBroadcast",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServerErrorBroadcast(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("ErrServerErrorBroadcast-Broadcast", ErrServerErrorBroadcastHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.ErrServerErrorBroadcast", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("ErrServerErrorBroadcast-Direct", ErrServerErrorBroadcastHandler, opts.Subject("service.TestService.ErrServerErrorBroadcast", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalBroadcastTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.NormalBroadcastTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("NormalBroadcastTestTest-Broadcast", NormalBroadcastTestTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalBroadcastTestTest-Direct", NormalBroadcastTestTestHandler, opts.Subject("service.TestService.NormalBroadcastTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalBroadcastEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.NormalBroadcastEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("NormalBroadcastEmptyTest-Broadcast", NormalBroadcastEmptyTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalBroadcastEmptyTest-Direct", NormalBroadcastEmptyTestHandler, opts.Subject("service.TestService.NormalBroadcastEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalBroadcastTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.NormalBroadcastTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("NormalBroadcastTestEmpty-Broadcast", NormalBroadcastTestEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalBroadcastTestEmpty-Direct", NormalBroadcastTestEmptyHandler, opts.Subject("service.TestService.NormalBroadcastTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	NormalBroadcastEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.NormalBroadcastEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("NormalBroadcastEmptyEmpty-Broadcast", NormalBroadcastEmptyEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("NormalBroadcastEmptyEmpty-Direct", NormalBroadcastEmptyEmptyHandler, opts.Subject("service.TestService.NormalBroadcastEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	ThreeSecondDelayHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ThreeSecondDelay",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.ThreeSecondDelay(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("ThreeSecondDelay", ThreeSecondDelayHandler, opts.Subject("service.TestService.ThreeSecondDelay", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("ThreeSecondDelay-Direct", ThreeSecondDelayHandler, opts.Subject("service.TestService.ThreeSecondDelay", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

}

func NewTestServiceNATSLeaderServer(nc *nats_go.Conn, server TestServiceNATSLeaderServer, opts ...protonats.ServerOption) micro.Service {
	service, options, err := impl.NewService("TestService", nc, server, opts...)
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	if setId, ok := server.(TestServiceId); ok {
		setId.SetTestServiceId(service.Info().ID)
	}
	_newTestServiceLeaderServer(service, server, options)
	return service
}

func _newTestServiceLeaderServer(service micro.Service, server TestServiceNATSLeaderServer, opts *impl.ServerOpts) {
	var err error
	_ = err
	LeaderOnlyTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.LeaderOnlyTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("LeaderOnlyTestTest", LeaderOnlyTestTestHandler, opts.Subject("service.TestService.LeaderOnlyTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyTestTest-Direct", LeaderOnlyTestTestHandler, opts.Subject("service.TestService.LeaderOnlyTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.LeaderOnlyEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("LeaderOnlyEmptyTest", LeaderOnlyEmptyTestHandler, opts.Subject("service.TestService.LeaderOnlyEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyEmptyTest-Direct", LeaderOnlyEmptyTestHandler, opts.Subject("service.TestService.LeaderOnlyEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.LeaderOnlyTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("LeaderOnlyTestEmpty", LeaderOnlyTestEmptyHandler, opts.Subject("service.TestService.LeaderOnlyTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyTestEmpty-Direct", LeaderOnlyTestEmptyHandler, opts.Subject("service.TestService.LeaderOnlyTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.LeaderOnlyEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("LeaderOnlyEmptyEmpty", LeaderOnlyEmptyEmptyHandler, opts.Subject("service.TestService.LeaderOnlyEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyEmptyEmpty-Direct", LeaderOnlyEmptyEmptyHandler, opts.Subject("service.TestService.LeaderOnlyEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyBroadcastTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyBroadcastTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.LeaderOnlyBroadcastTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("LeaderOnlyBroadcastTestTest-Broadcast", LeaderOnlyBroadcastTestTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.LeaderOnlyBroadcastTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyBroadcastTestTest-Direct", LeaderOnlyBroadcastTestTestHandler, opts.Subject("service.TestService.LeaderOnlyBroadcastTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyBroadcastEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyBroadcastEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.LeaderOnlyBroadcastEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("LeaderOnlyBroadcastEmptyTest-Broadcast", LeaderOnlyBroadcastEmptyTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.LeaderOnlyBroadcastEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyBroadcastEmptyTest-Direct", LeaderOnlyBroadcastEmptyTestHandler, opts.Subject("service.TestService.LeaderOnlyBroadcastEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyBroadcastTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyBroadcastTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.LeaderOnlyBroadcastTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("LeaderOnlyBroadcastTestEmpty-Broadcast", LeaderOnlyBroadcastTestEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.LeaderOnlyBroadcastTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyBroadcastTestEmpty-Direct", LeaderOnlyBroadcastTestEmptyHandler, opts.Subject("service.TestService.LeaderOnlyBroadcastTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	LeaderOnlyBroadcastEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "LeaderOnlyBroadcastEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.LeaderOnlyBroadcastEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("LeaderOnlyBroadcastEmptyEmpty-Broadcast", LeaderOnlyBroadcastEmptyEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.LeaderOnlyBroadcastEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("LeaderOnlyBroadcastEmptyEmpty-Direct", LeaderOnlyBroadcastEmptyEmptyHandler, opts.Subject("service.TestService.LeaderOnlyBroadcastEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

}

func NewTestServiceNATSFollowerServer(nc *nats_go.Conn, server TestServiceNATSFollowerServer, opts ...protonats.ServerOption) micro.Service {
	service, options, err := impl.NewService("TestService", nc, server, opts...)
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	if setId, ok := server.(TestServiceId); ok {
		setId.SetTestServiceId(service.Info().ID)
	}
	_newTestServiceFollowerServer(service, server, options)
	return service
}

func _newTestServiceFollowerServer(service micro.Service, server TestServiceNATSFollowerServer, opts *impl.ServerOpts) {
	var err error
	_ = err
	FollowerOnlyTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.FollowerOnlyTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("FollowerOnlyTestTest", FollowerOnlyTestTestHandler, opts.Subject("service.TestService.FollowerOnlyTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyTestTest-Direct", FollowerOnlyTestTestHandler, opts.Subject("service.TestService.FollowerOnlyTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.FollowerOnlyEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("FollowerOnlyEmptyTest", FollowerOnlyEmptyTestHandler, opts.Subject("service.TestService.FollowerOnlyEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyEmptyTest-Direct", FollowerOnlyEmptyTestHandler, opts.Subject("service.TestService.FollowerOnlyEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.FollowerOnlyTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("FollowerOnlyTestEmpty", FollowerOnlyTestEmptyHandler, opts.Subject("service.TestService.FollowerOnlyTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyTestEmpty-Direct", FollowerOnlyTestEmptyHandler, opts.Subject("service.TestService.FollowerOnlyTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.FollowerOnlyEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("FollowerOnlyEmptyEmpty", FollowerOnlyEmptyEmptyHandler, opts.Subject("service.TestService.FollowerOnlyEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyEmptyEmpty-Direct", FollowerOnlyEmptyEmptyHandler, opts.Subject("service.TestService.FollowerOnlyEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyBroadcastTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyBroadcastTestTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.FollowerOnlyBroadcastTestTest(ctx, typedReq)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("FollowerOnlyBroadcastTestTest-Broadcast", FollowerOnlyBroadcastTestTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.FollowerOnlyBroadcastTestTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyBroadcastTestTest-Direct", FollowerOnlyBroadcastTestTestHandler, opts.Subject("service.TestService.FollowerOnlyBroadcastTestTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyBroadcastEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyBroadcastEmptyTest",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.FollowerOnlyBroadcastEmptyTest(ctx)
		}

		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()))
			return
		}
		request.Respond(data)
	})
	err = service.AddEndpoint("FollowerOnlyBroadcastEmptyTest-Broadcast", FollowerOnlyBroadcastEmptyTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.FollowerOnlyBroadcastEmptyTest", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyBroadcastEmptyTest-Direct", FollowerOnlyBroadcastEmptyTestHandler, opts.Subject("service.TestService.FollowerOnlyBroadcastEmptyTest", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyBroadcastTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()))
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyBroadcastTestEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.FollowerOnlyBroadcastTestEmpty(ctx, typedReq)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("FollowerOnlyBroadcastTestEmpty-Broadcast", FollowerOnlyBroadcastTestEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.FollowerOnlyBroadcastTestEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyBroadcastTestEmpty-Direct", FollowerOnlyBroadcastTestEmptyHandler, opts.Subject("service.TestService.FollowerOnlyBroadcastTestEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

	FollowerOnlyBroadcastEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := context.Background()
		ctx = impl.NewContextWithHeaders(ctx, nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "FollowerOnlyBroadcastEmptyEmpty",
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.FollowerOnlyBroadcastEmptyEmpty(ctx)
		}

		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders())
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()))
			}
			return
		}

		request.Respond(nil)
	})
	err = service.AddEndpoint("FollowerOnlyBroadcastEmptyEmpty-Broadcast", FollowerOnlyBroadcastEmptyEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.FollowerOnlyBroadcastEmptyEmpty", ""))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}
	err = service.AddEndpoint("FollowerOnlyBroadcastEmptyEmpty-Direct", FollowerOnlyBroadcastEmptyEmptyHandler, opts.Subject("service.TestService.FollowerOnlyBroadcastEmptyEmpty", service.Info().ID))
	if err != nil {
		panic(err) // TODO: Update this to proper error handling
	}

}

//endregion
