syntax = "proto3";

package protonats.go.test;

import "google/protobuf/empty.proto";
import "protonats.proto";

option go_package = "xiam.li/go-protonats/internal/test";

service TestService {
  // Normal tests
  rpc NormalTestTest(Test) returns (Test);
  rpc NormalEmptyTest(google.protobuf.Empty) returns (Test);
  rpc NormalTestEmpty(Test) returns (google.protobuf.Empty);
  rpc NormalEmptyEmpty(google.protobuf.Empty) returns (google.protobuf.Empty);

  // Methods that will expect an error in the test implementation
  rpc ErrServiceError(Test) returns (Test);
  rpc ErrServerError(Test) returns (Test);
  rpc ErrServiceErrorBroadcast(Test) returns (Test) {
    option (protonats.broadcast) = true;
  }
  rpc ErrServerErrorBroadcast(Test) returns (Test) {
    option (protonats.broadcast) = true;
  }

  // Normal tests with broadcast option
  rpc NormalBroadcastTestTest(Test) returns (Test) {
    option (protonats.broadcast) = true;
  }
  rpc NormalBroadcastEmptyTest(google.protobuf.Empty) returns (Test) {
    option (protonats.broadcast) = true;
  }
  rpc NormalBroadcastTestEmpty(Test) returns (google.protobuf.Empty) {
    option (protonats.broadcast) = true;
  }
  rpc NormalBroadcastEmptyEmpty(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (protonats.broadcast) = true;
  }

  // Special cases
  rpc ThreeSecondDelay(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message Test {
  string test = 1;
}
