// Code generated by protoc-gen-go-nats. DO NOT EDIT.
// Versions:
// - protoc-gen-go-nats v0.1.14-dev.37+dirty
// - protoc        v6.33.2
// source: test.proto

package test

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"
	nats_go "github.com/nats-io/nats.go"
	micro "github.com/nats-io/nats.go/micro"
	nuid "github.com/nats-io/nuid"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	sync "sync"
	time "time"
	impl "xiam.li/protonats/go/impl"
	protonats "xiam.li/protonats/go/protonats"
)

// region Client
type TestServiceNATSClient interface {
	// Normal tests
	NormalTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	NormalEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error)
	NormalTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error
	NormalEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error
	// Methods that will expect an error in the test implementation
	ErrServiceError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	ErrServerError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error)
	ErrServiceErrorBroadcast(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	ErrServerErrorBroadcast(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	// Normal tests with broadcast option
	NormalBroadcastTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	NormalBroadcastEmptyTest(ctx context.Context, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error)
	NormalBroadcastTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	NormalBroadcastEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) ([]protonats.ServiceError, error)
	// Special cases
	ThreeSecondDelay(ctx context.Context, opts ...protonats.CallOption) error
	SetTimeout(time.Duration)
	// ListInstances returns a list containing all instances of this service
	// This is a convenience method that calls protonats.Ping with no options
	ListInstances(ctx context.Context) ([]*protonats.Ping, error)
	// Ping sends a ping to either all instances or a specific instance of this service
	Ping(ctx context.Context, opts ...protonats.CallOption) ([]*protonats.Ping, error)
	// Stats returns the stats of either all instances or a specific instance of this service
	Stats(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Stats, error)
	// Info returns the info of either all instances or a specific instance of this service
	Info(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Info, error)
}

type testServiceNATSClient struct {
	nc          *nats_go.Conn
	timeout     time.Duration
	interceptor protonats.UnaryClientInterceptor
}

func (c *testServiceNATSClient) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *testServiceNATSClient) ListInstances(ctx context.Context) ([]*protonats.Ping, error) {
	return c.Ping(ctx)
}

func (c *testServiceNATSClient) Stats(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Stats, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.STATS.TestService", nil, func(data []byte, rtt time.Duration) (*micro.Stats, error) {
		var obj micro.Stats
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) Info(ctx context.Context, opts ...protonats.CallOption) ([]*micro.Info, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.INFO.TestService", nil, func(data []byte, rtt time.Duration) (*micro.Info, error) {
		var obj micro.Info
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) Ping(ctx context.Context, opts ...protonats.CallOption) ([]*protonats.Ping, error) {
	objs, _, err := request(ctx, c.nc, c.timeout, "$SRV.PING.TestService", nil, func(data []byte, rtt time.Duration) (*protonats.Ping, error) {
		var obj protonats.Ping
		if err := json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		obj.RTT = rtt
		return &obj, nil
	}, opts...)
	return objs, err
}

func (c *testServiceNATSClient) handle(ctx context.Context, req proto.Message, info *protonats.MethodInfo, out proto.Message, opts ...protonats.CallOption) error {
	var headerMap nats_go.Header
	if ctxHeaders := protonats.HeadersFromOutgoingContext(ctx); ctxHeaders != nil {
		headerMap = nats_go.Header(ctxHeaders)
		for key, values := range headerMap {
			headerMap[key] = values
		}
	} else {
		headerMap = nats_go.Header{}
	}

	invoker := invoker(c.nc)

	if c.interceptor == nil {
		return invoker(ctx, info, req, out, headerMap, opts...)
	} else {
		return c.interceptor(ctx, info, req, out, headerMap, invoker, opts...)
	}
}

func invoker(conn *nats_go.Conn) protonats.UnaryInvoker {
	return func(ctx context.Context, info *protonats.MethodInfo, req proto.Message, reply proto.Message, header nats_go.Header, opts ...protonats.CallOption) error {
		options := impl.ProcessCallOptions(opts...)

		var cancel context.CancelFunc
		if _, hasDeadline := ctx.Deadline(); !hasDeadline {
			timeout := options.GetTimeoutOr(5 * time.Second)
			ctx, cancel = context.WithTimeout(ctx, timeout)
			defer cancel()
		}

		data, err := proto.Marshal(req)
		if err != nil {
			return protonats.ServiceError{Code: protonats.ErrMarshallingFailed.Code(), Description: protonats.ErrMarshallingFailed.String(), Details: err.Error()}
		}

		subject := options.Subject(info.Subject)
		msg := &nats_go.Msg{
			Subject: subject,
			Data:    data,
			Header:  header,
		}

		respMsg, err := conn.RequestMsgWithContext(ctx, msg)
		if err != nil {
			return err
		}

		options.ApplyResponseHeaders(respMsg.Header)

		if errMsg, errCode := respMsg.Header.Get(micro.ErrorHeader), respMsg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
			if len(respMsg.Data) == 0 {
				return protonats.ServiceError{Code: errCode, Description: errMsg}
			}
			return protonats.ServiceError{Code: errCode, Description: errMsg, Details: string(respMsg.Data)}
		}
		if reply != nil {
			if err = proto.Unmarshal(respMsg.Data, reply); err != nil {
				return protonats.ServiceError{Code: protonats.ErrUnmarshallingFailed.Code(), Description: protonats.ErrUnmarshallingFailed.String(), Details: err.Error()}
			}
		}
		return nil
	}
}

func request[T any](ctx context.Context, conn *nats_go.Conn, timeout time.Duration, subject string, data []byte, collector func([]byte, time.Duration) (*T, error), opts ...protonats.CallOption) ([]*T, []protonats.ServiceError, error) {
	options := impl.ProcessCallOptions(opts...)
	timeout = options.GetTimeoutOr(timeout)

	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	timer := time.NewTimer(timeout)
	go func() {
		select {
		case <-timer.C:
			cancel()
		case <-ctx.Done():
			timer.Stop()
			return
		}
	}()
	var start time.Time
	res := []*T{}
	mu := sync.Mutex{}
	errCh := make(chan error)
	serviceErrs := []protonats.ServiceError{}
	var finisher *time.Timer
	if !options.DisableFinisher {
		finisher = time.NewTimer(timeout)
		go func() {
			select {
			case <-finisher.C:
				cancel()
			case <-ctx.Done():
				return
			}
		}()
	}
	sub, err := conn.Subscribe(conn.NewRespInbox(), func(msg *nats_go.Msg) {
		mu.Lock()
		defer mu.Unlock()

		rtt := time.Since(start)
		if msg.Header.Get("Status") == "503" {
			errCh <- nats_go.ErrNoResponders
			return
		}

		if finisher != nil {
			finisher.Reset(250 * time.Millisecond)
		}

		if errMsg, errCode := msg.Header.Get(micro.ErrorHeader), msg.Header.Get(micro.ErrorCodeHeader); len(errMsg) > 0 && len(errCode) > 0 {
			if len(msg.Data) == 0 {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg})
			} else {
				serviceErrs = append(serviceErrs, protonats.ServiceError{Code: errCode, Description: errMsg, Details: string(msg.Data)})
			}
			return
		}
		if collector != nil {
			if col, err := collector(msg.Data, rtt); err != nil {
				errCh <- err
			} else {
				res = append(res, col)
			}
		}
	})
	if err != nil {
		return nil, nil, err
	}
	defer sub.Unsubscribe()

	start = time.Now()
	err = conn.PublishRequest(options.Subject(subject), sub.Subject, data)
	if err != nil {
		return nil, nil, err
	}

	select {
	case err = <-errCh:
		return nil, serviceErrs, err
	case <-ctx.Done():
		return res, serviceErrs, nil
	}
}

func NewTestServiceNATSClient(nc *nats_go.Conn, opts ...protonats.ClientOption) TestServiceNATSClient {
	clientOpts := impl.ProcessClientOptions(opts...)
	return &testServiceNATSClient{nc: nc, timeout: time.Second * 5, interceptor: clientOpts.UnaryInterceptor}
}

func (c *testServiceNATSClient) NormalTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalTestTest",
		Service: "TestService",
		Method:  "NormalTestTest",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, req, info, &response, opts...); err != nil {
		return nil, err
	}
	return &response, nil
}

func (c *testServiceNATSClient) NormalEmptyTest(ctx context.Context, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalEmptyTest",
		Service: "TestService",
		Method:  "NormalEmptyTest",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, nil, info, &response, opts...); err != nil {
		return nil, err
	}
	return &response, nil
}

func (c *testServiceNATSClient) NormalTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalTestEmpty",
		Service: "TestService",
		Method:  "NormalTestEmpty",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, req, info, nil, opts...); err != nil {
		return err
	}
	return nil
}

func (c *testServiceNATSClient) NormalEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.NormalEmptyEmpty",
		Service: "TestService",
		Method:  "NormalEmptyEmpty",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, nil, info, nil, opts...); err != nil {
		return err
	}
	return nil
}

func (c *testServiceNATSClient) ErrServiceError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.ErrServiceError",
		Service: "TestService",
		Method:  "ErrServiceError",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, req, info, &response, opts...); err != nil {
		return nil, err
	}
	return &response, nil
}

func (c *testServiceNATSClient) ErrServerError(ctx context.Context, req *Test, opts ...protonats.CallOption) (*Test, error) {
	var response Test

	info := &protonats.MethodInfo{
		Subject: "service.TestService.ErrServerError",
		Service: "TestService",
		Method:  "ErrServerError",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, req, info, &response, opts...); err != nil {
		return nil, err
	}
	return &response, nil
}

func (c *testServiceNATSClient) ErrServiceErrorBroadcast(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ServiceError{Code: protonats.ErrMarshallingFailed.Code(), Description: protonats.ErrMarshallingFailed.String(), Details: err.Error()}
		}
	}
	objs, serviceErrs, err := request(ctx, c.nc, c.timeout, "service.TestService.ErrServiceErrorBroadcast", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) ErrServerErrorBroadcast(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ServiceError{Code: protonats.ErrMarshallingFailed.Code(), Description: protonats.ErrMarshallingFailed.String(), Details: err.Error()}
		}
	}
	objs, serviceErrs, err := request(ctx, c.nc, c.timeout, "service.TestService.ErrServerErrorBroadcast", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastTestTest(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, nil, protonats.ServiceError{Code: protonats.ErrMarshallingFailed.Code(), Description: protonats.ErrMarshallingFailed.String(), Details: err.Error()}
		}
	}
	objs, serviceErrs, err := request(ctx, c.nc, c.timeout, "service.TestService.NormalBroadcastTestTest", data, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastEmptyTest(ctx context.Context, opts ...protonats.CallOption) ([]*Test, []protonats.ServiceError, error) {
	objs, serviceErrs, err := request(ctx, c.nc, c.timeout, "service.TestService.NormalBroadcastEmptyTest", nil, func(data []byte, rtt time.Duration) (*Test, error) {
		var obj Test
		if err := proto.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	}, opts...)
	return objs, serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastTestEmpty(ctx context.Context, req *Test, opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	var data []byte
	if req != nil {
		var err error
		if data, err = proto.Marshal(req); err != nil {
			return nil, protonats.ServiceError{Code: protonats.ErrMarshallingFailed.Code(), Description: protonats.ErrMarshallingFailed.String(), Details: err.Error()}
		}
	}
	_, serviceErrs, err := request[struct{}](ctx, c.nc, c.timeout, "service.TestService.NormalBroadcastTestEmpty", data, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) NormalBroadcastEmptyEmpty(ctx context.Context, opts ...protonats.CallOption) ([]protonats.ServiceError, error) {
	_, serviceErrs, err := request[struct{}](ctx, c.nc, c.timeout, "service.TestService.NormalBroadcastEmptyEmpty", nil, nil, opts...)
	return serviceErrs, err
}

func (c *testServiceNATSClient) ThreeSecondDelay(ctx context.Context, opts ...protonats.CallOption) error {
	info := &protonats.MethodInfo{
		Subject: "service.TestService.ThreeSecondDelay",
		Service: "TestService",
		Method:  "ThreeSecondDelay",
		Type:    protonats.MethodTypeUnary,
	}

	if err := c.handle(ctx, nil, info, nil, opts...); err != nil {
		return err
	}
	return nil
}

//endregion

// region Server
type TestServiceNATSServer interface {
	// Normal tests
	NormalTestTest(ctx context.Context, req *Test) (*Test, error)
	NormalEmptyTest(ctx context.Context) (*Test, error)
	NormalTestEmpty(ctx context.Context, req *Test) error
	NormalEmptyEmpty(ctx context.Context) error
	// Methods that will expect an error in the test implementation
	ErrServiceError(ctx context.Context, req *Test) (*Test, error)
	ErrServerError(ctx context.Context, req *Test) (*Test, error)
	ErrServiceErrorBroadcast(ctx context.Context, req *Test) (*Test, error)
	ErrServerErrorBroadcast(ctx context.Context, req *Test) (*Test, error)
	// Normal tests with broadcast option
	NormalBroadcastTestTest(ctx context.Context, req *Test) (*Test, error)
	NormalBroadcastEmptyTest(ctx context.Context) (*Test, error)
	NormalBroadcastTestEmpty(ctx context.Context, req *Test) error
	NormalBroadcastEmptyEmpty(ctx context.Context) error
	// Special cases
	ThreeSecondDelay(ctx context.Context) error
}

type TestServiceId interface {
	SetTestServiceId(string)
}

func NewTestServiceNATSServer(nc *nats_go.Conn, server TestServiceNATSServer, opts ...protonats.ServerOption) (micro.Service, error) {
	service, options, err := impl.NewService("TestService", nc, server, opts...)
	if err != nil {
		return nil, err
	}

	if setId, ok := server.(TestServiceId); ok {
		setId.SetTestServiceId(service.Info().ID)
	}

	if err := _newTestServiceServer(service, server, options); err != nil {
		if serviceErr := service.Stop(); serviceErr != nil {
			return nil, errors.Join(
				fmt.Errorf("failed to create service: %w", err),
				fmt.Errorf("failed to stop service after creation failure: %w", serviceErr),
			)
		}
		return nil, fmt.Errorf("failed to create service: %w", err)
	}

	return service, nil
}

func _newTestServiceServer(service micro.Service, server TestServiceNATSServer, opts *impl.ServerOpts) error {
	serviceIDHeaderOpt := micro.WithHeaders(micro.Headers{impl.ServiceIDHeader: []string{service.Info().ID}})

	// Register the service's methods
	NormalTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalTestTest",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.NormalTestTest(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalTestTest", NormalTestTestHandler, opts.Subject("service.TestService.NormalTestTest", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalTestTest-Direct", NormalTestTestHandler, opts.Subject("service.TestService.NormalTestTest", service.Info().ID)); err != nil {
		return err
	}

	NormalEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalEmptyTest",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.NormalEmptyTest(ctx)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalEmptyTest", NormalEmptyTestHandler, opts.Subject("service.TestService.NormalEmptyTest", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalEmptyTest-Direct", NormalEmptyTestHandler, opts.Subject("service.TestService.NormalEmptyTest", service.Info().ID)); err != nil {
		return err
	}

	NormalTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalTestEmpty",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.NormalTestEmpty(ctx, typedReq)
		}

		var err error
		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		request.Respond(nil, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalTestEmpty", NormalTestEmptyHandler, opts.Subject("service.TestService.NormalTestEmpty", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalTestEmpty-Direct", NormalTestEmptyHandler, opts.Subject("service.TestService.NormalTestEmpty", service.Info().ID)); err != nil {
		return err
	}

	NormalEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalEmptyEmpty",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.NormalEmptyEmpty(ctx)
		}

		var err error
		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		request.Respond(nil, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalEmptyEmpty", NormalEmptyEmptyHandler, opts.Subject("service.TestService.NormalEmptyEmpty", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalEmptyEmpty-Direct", NormalEmptyEmptyHandler, opts.Subject("service.TestService.NormalEmptyEmpty", service.Info().ID)); err != nil {
		return err
	}

	ErrServiceErrorHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServiceError",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServiceError(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("ErrServiceError", ErrServiceErrorHandler, opts.Subject("service.TestService.ErrServiceError", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("ErrServiceError-Direct", ErrServiceErrorHandler, opts.Subject("service.TestService.ErrServiceError", service.Info().ID)); err != nil {
		return err
	}

	ErrServerErrorHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServerError",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServerError(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("ErrServerError", ErrServerErrorHandler, opts.Subject("service.TestService.ErrServerError", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("ErrServerError-Direct", ErrServerErrorHandler, opts.Subject("service.TestService.ErrServerError", service.Info().ID)); err != nil {
		return err
	}

	ErrServiceErrorBroadcastHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServiceErrorBroadcast",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServiceErrorBroadcast(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("ErrServiceErrorBroadcast-Broadcast", ErrServiceErrorBroadcastHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.ErrServiceErrorBroadcast", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("ErrServiceErrorBroadcast-Direct", ErrServiceErrorBroadcastHandler, opts.Subject("service.TestService.ErrServiceErrorBroadcast", service.Info().ID)); err != nil {
		return err
	}

	ErrServerErrorBroadcastHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ErrServerErrorBroadcast",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.ErrServerErrorBroadcast(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("ErrServerErrorBroadcast-Broadcast", ErrServerErrorBroadcastHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.ErrServerErrorBroadcast", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("ErrServerErrorBroadcast-Direct", ErrServerErrorBroadcastHandler, opts.Subject("service.TestService.ErrServerErrorBroadcast", service.Info().ID)); err != nil {
		return err
	}

	NormalBroadcastTestTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastTestTest",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return server.NormalBroadcastTestTest(ctx, typedReq)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, &req)
		} else {
			response, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalBroadcastTestTest-Broadcast", NormalBroadcastTestTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastTestTest", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalBroadcastTestTest-Direct", NormalBroadcastTestTestHandler, opts.Subject("service.TestService.NormalBroadcastTestTest", service.Info().ID)); err != nil {
		return err
	}

	NormalBroadcastEmptyTestHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastEmptyTest",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return server.NormalBroadcastEmptyTest(ctx)
		}

		var err error
		var response proto.Message
		if opts == nil || opts.UnaryInterceptor == nil {
			response, err = handler(ctx, nil)
		} else {
			response, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		data, err := proto.Marshal(response)
		if err != nil {
			request.Error("560", "Failed to marshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}
		request.Respond(data, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalBroadcastEmptyTest-Broadcast", NormalBroadcastEmptyTestHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastEmptyTest", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalBroadcastEmptyTest-Direct", NormalBroadcastEmptyTestHandler, opts.Subject("service.TestService.NormalBroadcastEmptyTest", service.Info().ID)); err != nil {
		return err
	}

	NormalBroadcastTestEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		var req Test
		if err := proto.Unmarshal(request.Data(), &req); err != nil {
			request.Error("560", "Failed to unmarshal proto message", []byte(err.Error()), serviceIDHeaderOpt)
			return
		}

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastTestEmpty",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typedReq, ok := req.(*Test)
			if !ok {
				return nil, errors.New("invalid request type")
			}
			return nil, server.NormalBroadcastTestEmpty(ctx, typedReq)
		}

		var err error
		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, &req)
		} else {
			_, err = opts.UnaryInterceptor(ctx, &req, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		request.Respond(nil, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalBroadcastTestEmpty-Broadcast", NormalBroadcastTestEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastTestEmpty", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalBroadcastTestEmpty-Direct", NormalBroadcastTestEmptyHandler, opts.Subject("service.TestService.NormalBroadcastTestEmpty", service.Info().ID)); err != nil {
		return err
	}

	NormalBroadcastEmptyEmptyHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "NormalBroadcastEmptyEmpty",
			Type:    protonats.MethodTypeBroadcast,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.NormalBroadcastEmptyEmpty(ctx)
		}

		var err error
		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		request.Respond(nil, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("NormalBroadcastEmptyEmpty-Broadcast", NormalBroadcastEmptyEmptyHandler, micro.WithEndpointQueueGroup(nuid.Next()), opts.Subject("service.TestService.NormalBroadcastEmptyEmpty", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("NormalBroadcastEmptyEmpty-Direct", NormalBroadcastEmptyEmptyHandler, opts.Subject("service.TestService.NormalBroadcastEmptyEmpty", service.Info().ID)); err != nil {
		return err
	}

	ThreeSecondDelayHandler := micro.HandlerFunc(func(request micro.Request) {
		ctx := impl.NewContextWithHeaders(opts.Ctx(), nats_go.Header(request.Headers()))

		info := &protonats.MethodInfo{
			Subject: request.Subject(),
			Service: "TestService",
			Method:  "ThreeSecondDelay",
			Type:    protonats.MethodTypeUnary,
		}

		handler := func(ctx context.Context, req proto.Message) (proto.Message, error) {
			return nil, server.ThreeSecondDelay(ctx)
		}

		var err error
		if opts == nil || opts.UnaryInterceptor == nil {
			_, err = handler(ctx, nil)
		} else {
			_, err = opts.UnaryInterceptor(ctx, nil, info, handler)
		}

		if err != nil {
			if protonats.IsServiceError(err) {
				slog.Warn("Server implementations should not return ServiceError, use go_nats.NewServerError instead", "error", err)
			}
			var serverErr protonats.ServerError
			if errors.As(err, &serverErr) {
				request.Error(serverErr.Code, serverErr.Description, serverErr.GetWrapped(), serverErr.GetOptHeaders(), serviceIDHeaderOpt)
			} else {
				request.Error("500", "Internal server error", []byte(err.Error()), serviceIDHeaderOpt)
			}
			return
		}

		request.Respond(nil, serviceIDHeaderOpt)
	})
	if err := service.AddEndpoint("ThreeSecondDelay", ThreeSecondDelayHandler, opts.Subject("service.TestService.ThreeSecondDelay", "")); err != nil {
		return err
	}
	if err := service.AddEndpoint("ThreeSecondDelay-Direct", ThreeSecondDelayHandler, opts.Subject("service.TestService.ThreeSecondDelay", service.Info().ID)); err != nil {
		return err
	}

	return nil
}

//endregion
